# Generated by Django 4.1.4 on 2023-05-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('tags', models.TextField()),
                ('img', models.FileField(upload_to='pic/%y/')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
